### ISSUE TITLE
Define the targeting flags in build files, rather than source code

### ISSUE THREAD

**Issue by mtrofin** [njuwangchen/teapots_wasm_porting#1]
Consider defining the AND and WASM build controls in the respective build files, rather than various source files:
- the target is implied at build time (we don't build a mix of android and wasm-specific code)
- it avoids the risk of developer forgetting to set the flag in one of the files.

Also, please rename:
AND -> TARGET_ANDROID
WASM -> TARGET_WASM

**Comment by njuwangchen** [comment]
https://github.com/njuwangchen/teapots_wasm_porting/commit/9a603dd0f9a6faa2b7a29f2778601f9180784bca
