### ISSUE TITLE
Please clarify if/which config macros are orthogonal.

### ISSUE THREAD

**Issue by mtrofin** [njuwangchen/teapots_wasm_porting#2]
RE. https://github.com/njuwangchen/teapots_wasm_porting#macros - are all the macros orthogonal, or does enabling some exclude others? (Please clarify in Readme).

If some exclude others, consider formally checking that and #error-ing.

**Comment by njuwangchen** [comment]
https://github.com/njuwangchen/teapots_wasm_porting/commit/6edc428d67824fe2102bedab7164ecf85849c032

https://github.com/njuwangchen/teapots_wasm_porting/commit/72e2f1a647a1fd7c7e6478c0aacdda933ff3d3bd

https://github.com/njuwangchen/teapots_wasm_porting/commit/74c2ca8abd8423772367015bd1c937cf8af55bd3

resolve this issue.
